In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np

In [3]:
import pandas as pd

path='/content/drive/Shareddrives/캡스톤디자인/동서기공 RUL data/max_points.json'

data=pd.read_json(path)

In [4]:
data

,index,regDate,itemType,srcData,toolPreset,toolCount,start,end,len,path,completion,failure,RUL,src_crop,new_len,max_points
0,4593,1641670911000,normal_cycle,"[1016, 9415, 16709, 16064, 11858, 8672, 6277, ...",350,1,34,2282,2248,2,1,346,345,"[178, 178, 177, 182, 188, 190, 194, 195, 197, ...",2089,"[1383, 1562, 1254, 1228, 1116, 1078, 1065, 109..."
1,4594,1641671740000,normal_cycle,"[7900, 15727, 16978, 12575, 9201, 6668, 4799, ...",350,2,31,2278,2247,2,1,346,344,"[190, 191, 192, 195, 194, 198, 198, 199, 202, ...",2090,"[1342, 1636, 1276, 1194, 1106, 1049, 1063, 108..."
2,4595,1641672182000,normal_cycle,"[4617, 13439, 17742, 13861, 10176, 7405, 5351,...",350,3,32,2281,2249,2,1,346,343,"[177, 178, 179, 182, 187, 191, 199, 217, 235, ...",2086,"[1299, 1362, 1205, 1173, 1135, 1107, 1119, 117..."
3,4596,1641672628000,normal_cycle,"[14619, 17415, 13137, 9635, 6996, 5048, 3622, ...",350,4,34,2281,2247,2,1,346,342,"[191, 192, 194, 194, 193, 193, 195, 195, 198, ...",2089,"[1370, 1566, 1167, 1182, 1178, 1156, 1127, 114..."
4,4597,1641673071000,normal_cycle,"[13438, 17697, 13811, 10151, 7394, 5336, 3829,...",350,5,35,2282,2247,2,1,346,341,"[174, 185, 209, 239, 265, 288, 312, 334, 356, ...",2081,"[1332, 1600, 1255, 1201, 1160, 1061, 1105, 113..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28117,37249,1660174125000,normal_cycle,"[67, 425, 7930, 15747, 17117, 12702, 9306, 675...",350,339,15,2264,2249,9,96,343,4,"[186, 187, 189, 190, 193, 196, 198, 199, 201, ...",2087,"[2352, 2745, 1673, 1523, 1679, 1430, 2027, 206..."
28118,37250,1660174633000,normal_cycle,"[61, 59, 57, 55, 52, 1970, 10859, 17452, 15496...",350,340,9,2261,2252,9,96,343,3,"[212, 212, 212, 208, 204, 200, 195, 194, 194, ...",2091,"[2127, 2585, 1620, 1516, 1537, 1521, 1945, 210..."
28119,37251,1660175076000,normal_cycle,"[1042, 9434, 16739, 16256, 12005, 8786, 6369, ...",350,341,16,2264,2248,9,96,343,2,"[211, 212, 212, 209, 208, 209, 209, 209, 205, ...",2089,"[2533, 2670, 1924, 2272, 2353, 1691, 2281, 236..."
28120,37252,1660175546000,normal_cycle,"[73, 65, 4649, 13461, 17790, 13918, 10234, 744...",350,342,15,2264,2249,9,96,343,1,"[204, 204, 201, 200, 198, 193, 186, 179, 177, ...",2088,"[2468, 2677, 2020, 2226, 2107, 1617, 2333, 239..."
28121,37253,1660176026000,normal_cycle,"[1032, 9426, 16733, 16248, 12000, 8783, 6363, ...",350,343,14,2261,2247,9,96,343,0,"[200, 200, 201, 201, 203, 203, 200, 196, 195, ...",2090,"[2239, 2463, 1746, 1721, 1751, 1806, 2123, 210..."

In [5]:
import statistics
data['src_median']=''
for i in range(len(data)):
    data['src_median'][i] = statistics.median(data['max_points'][i])

<ipython-input-5-3fa36c4c0368>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['src_median'][i] = statistics.median(data['max_points'][i])

In [ ]:
data['src_median']

0        1221
1        1194
2        1173
3        1178
4        1194
         ...
19786    1142
19787    1023
19788     940
19789    1029
19790    1057
Name: src_median, Length: 19791, dtype: object

In [6]:
data['src_Q1']=''
data['src_Q3']=''
data['src_sd']=''

for i in range(len(data)):
    data['src_Q1'][i] = pd.Series(data['max_points'][i]).quantile(0.25)
    data['src_Q3'][i] = pd.Series(data['max_points'][i]).quantile(0.75)
    data['src_sd'][i] = np.var(data['max_points'][i])

<ipython-input-6-3a7abfafb891>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['src_Q1'][i] = pd.Series(data['max_points'][i]).quantile(0.25)
<ipython-input-6-3a7abfafb891>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['src_Q3'][i] = pd.Series(data['max_points'][i]).quantile(0.75)
<ipython-input-6-3a7abfafb891>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['src_sd'][i] = np.var(data['max_points'][i])

In [ ]:
data.to_json('/content/drive/Shareddrives/캡스톤디자인/동서기공 RUL data/max_points_plus.json')

In [18]:
path1 = "/content/drive/Shareddrives/캡스톤디자인/동서기공 RUL data/data_real_final"

df=pd.read_json(path1)

In [19]:
df

,index,regDate,itemType,srcData,toolPreset,toolCount,start,end,len,path,...,alarm_max,alarm_mean,alarm_min,count_max,count_min,count_mean,src_sum,src_mean,src_max,src_min
0,4593,1641670911000,normal_cycle,"[1016, 9415, 16709, 16064, 11858, 8672, 6277, ...",350,1,34,2282,2248,2,...,1456,702.0,0,134,0,23,1145352,548.277645,1934,170
1,4594,1641671740000,normal_cycle,"[7900, 15727, 16978, 12575, 9201, 6668, 4799, ...",350,2,31,2278,2247,2,...,1456,702.0,0,152,0,36,1159934,554.992344,2047,174
2,4595,1641672182000,normal_cycle,"[4617, 13439, 17742, 13861, 10176, 7405, 5351,...",350,3,32,2281,2249,2,...,1456,702.0,0,98,0,24,1111542,532.858102,1911,172
3,4596,1641672628000,normal_cycle,"[14619, 17415, 13137, 9635, 6996, 5048, 3622, ...",350,4,34,2281,2247,2,...,1456,702.0,0,120,0,16,1118686,535.512685,1839,172
4,4597,1641673071000,normal_cycle,"[13438, 17697, 13811, 10151, 7394, 5336, 3829,...",350,5,35,2282,2247,2,...,1456,702.0,0,118,0,17,1112840,534.762134,1867,171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28117,37249,1660174125000,normal_cycle,"[67, 425, 7930, 15747, 17117, 12702, 9306, 675...",350,339,15,2264,2249,9,...,1573,338.0,0,409,0,17,2015158,965.576425,3180,186
28118,37250,1660174633000,normal_cycle,"[61, 59, 57, 55, 52, 1970, 10859, 17452, 15496...",350,340,9,2261,2252,9,...,1573,338.0,0,363,0,34,1909365,913.134864,2817,186
28119,37251,1660175076000,normal_cycle,"[1042, 9434, 16739, 16256, 12005, 8786, 6369, ...",350,341,16,2264,2248,9,...,1573,338.0,0,558,0,20,2215645,1060.624701,3023,186
28120,37252,1660175546000,normal_cycle,"[73, 65, 4649, 13461, 17790, 13918, 10234, 744...",350,342,15,2264,2249,9,...,1573,338.0,0,536,0,14,2225681,1065.939176,3341,177
28121,37253,1660176026000,normal_cycle,"[1032, 9426, 16733, 16248, 12000, 8783, 6363, ...",350,343,14,2261,2247,9,...,1573,338.0,0,423,0,22,2063965,987.543062,2909,183

In [20]:
data= df

In [12]:
len(data)

28122

In [21]:
data['sum_cumulative']=[0]*28122

In [22]:
data['max_cumulative']= [0]*28122
data['sum_cumulative']=[0]*28122

In [24]:
for j in (list(data['completion'].unique())):
    a=True
    for i in range(len(data)):
        if a==True:
            if data['completion'][i] == j:
                data['max_cumulative'][i] = data['src_max'][i]
                a=False
                

        
        else:
            data['max_cumulative'][i] =  data['max_cumulative'][i-1] + data['src_max'][i]

<ipython-input-24-6cce6e6ddc98>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['max_cumulative'][i] = data['src_max'][i]
<ipython-input-24-6cce6e6ddc98>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['max_cumulative'][i] =  data['max_cumulative'][i-1] + data['src_max'][i]

In [25]:


for j in (list(data['completion'].unique())):
    a=True
    for i in range(len(data)):
        if a==True:
            if data['completion'][i] == j:
                data['sum_cumulative'][i] = data['src_sum'][i]
                a=False
                

        
        else:
            data['sum_cumulative'][i] =  data['sum_cumulative'][i-1] + data['src_sum'][i]

<ipython-input-25-daab39fce8d0>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['sum_cumulative'][i] = data['src_sum'][i]
<ipython-input-25-daab39fce8d0>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['sum_cumulative'][i] =  data['sum_cumulative'][i-1] + data['src_sum'][i]

In [ ]:
df[df['completion']==2]

,index,regDate,itemType,srcData,toolPreset,toolCount,start,end,len,path,...,count_min,count_mean,src_sum,src_mean,src_max,src_min,reconstruction_error_stand,aaa,max_cumulative,sum_cumulative
342,4936,1641844735000,normal_cycle,"[9427, 16700, 15916, 11737, 8576, 6200, 4460, ...",350,1,31,2280,2249,2,...,0,37,943342,452.008625,1429,170,-1.343579,961.272727,1429,943342
343,4937,1641845213000,normal_cycle,"[1948, 10844, 17388, 15316, 11280, 8235, 5951,...",350,2,34,2284,2250,2,...,0,35,955530,458.068073,1430,168,0.107280,962.636364,2859,1898872
344,4938,1641845687000,normal_cycle,"[1950, 10845, 17379, 15290, 11266, 8228, 5945,...",350,3,33,2283,2250,2,...,0,36,951447,457.206631,1425,170,-0.551240,987.000000,4284,2850319
345,4939,1641846158000,normal_cycle,"[14618, 17403, 13114, 9618, 6988, 5047, 3622, ...",350,4,35,2282,2247,2,...,0,35,969163,465.049424,1657,170,-0.652396,969.090909,5941,3819482
346,4940,1641846633000,normal_cycle,"[7901, 15727, 16974, 12583, 9228, 6696, 4816, ...",350,5,35,2284,2249,2,...,0,35,930155,445.050239,1399,171,-1.370343,938.909091,7340,4749637
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
663,5258,1642011932000,normal_cycle,"[10848, 17373, 15270, 11251, 8214, 5942, 4277,...",350,329,36,2284,2248,2,...,0,15,1370119,655.873145,2457,173,1.002885,1543.272727,637438,369110407
664,5259,1642012410000,normal_cycle,"[12180, 17698, 14541, 10694, 7808, 5649, 4060,...",350,330,33,2281,2248,2,...,0,11,1351871,649.937981,2332,172,-0.234517,1581.090909,639770,370462278
665,5260,1642012885000,normal_cycle,"[9421, 16723, 16181, 11940, 8730, 6336, 4560, ...",350,331,34,2283,2249,2,...,0,15,1325791,634.957375,2159,171,-0.451395,1541.181818,641929,371788069
666,5261,1642013358000,normal_cycle,"[1954, 10848, 17435, 15452, 11382, 8313, 6009,...",350,332,35,2285,2250,2,...,0,13,1387169,664.352969,2507,170,-0.352569,1602.272727,644436,373175238
667,5262,1642013830000,normal_cycle,"[9418, 16704, 16008, 11810, 8628, 6244, 4502, ...",350,333,34,2283,2249,2,...,0,14,1365123,655.049424,2417,166,-0.498837,1542.727273,646853,374540361

In [26]:
data

,index,regDate,itemType,srcData,toolPreset,toolCount,start,end,len,path,...,alarm_min,count_max,count_min,count_mean,src_sum,src_mean,src_max,src_min,sum_cumulative,max_cumulative
0,4593,1641670911000,normal_cycle,"[1016, 9415, 16709, 16064, 11858, 8672, 6277, ...",350,1,34,2282,2248,2,...,0,134,0,23,1145352,548.277645,1934,170,1145352,1934
1,4594,1641671740000,normal_cycle,"[7900, 15727, 16978, 12575, 9201, 6668, 4799, ...",350,2,31,2278,2247,2,...,0,152,0,36,1159934,554.992344,2047,174,2305286,3981
2,4595,1641672182000,normal_cycle,"[4617, 13439, 17742, 13861, 10176, 7405, 5351,...",350,3,32,2281,2249,2,...,0,98,0,24,1111542,532.858102,1911,172,3416828,5892
3,4596,1641672628000,normal_cycle,"[14619, 17415, 13137, 9635, 6996, 5048, 3622, ...",350,4,34,2281,2247,2,...,0,120,0,16,1118686,535.512685,1839,172,4535514,7731
4,4597,1641673071000,normal_cycle,"[13438, 17697, 13811, 10151, 7394, 5336, 3829,...",350,5,35,2282,2247,2,...,0,118,0,17,1112840,534.762134,1867,171,5648354,9598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28117,37249,1660174125000,normal_cycle,"[67, 425, 7930, 15747, 17117, 12702, 9306, 675...",350,339,15,2264,2249,9,...,0,409,0,17,2015158,965.576425,3180,186,511428499,763387
28118,37250,1660174633000,normal_cycle,"[61, 59, 57, 55, 52, 1970, 10859, 17452, 15496...",350,340,9,2261,2252,9,...,0,363,0,34,1909365,913.134864,2817,186,513337864,766204
28119,37251,1660175076000,normal_cycle,"[1042, 9434, 16739, 16256, 12005, 8786, 6369, ...",350,341,16,2264,2248,9,...,0,558,0,20,2215645,1060.624701,3023,186,515553509,769227
28120,37252,1660175546000,normal_cycle,"[73, 65, 4649, 13461, 17790, 13918, 10234, 744...",350,342,15,2264,2249,9,...,0,536,0,14,2225681,1065.939176,3341,177,517779190,772568
28121,37253,1660176026000,normal_cycle,"[1032, 9426, 16733, 16248, 12000, 8783, 6363, ...",350,343,14,2261,2247,9,...,0,423,0,22,2063965,987.543062,2909,183,519843155,775477

In [27]:
data.to_json('/content/drive/Shareddrives/캡스톤디자인/동서기공 RUL data/data_1212.json')